# 迷宫配置
title = "默认迷宫配置"

# 迷宫布局
# true 表示可行走的格子，false 表示墙壁
maze = [
    [true, true, true, true, true, true],
    [true, true, true, false, true, true],
    [true, true, true, true, true, true],
    [true, false, true, false, true, true],
    [true, true, true, true, true, true],
    [true, true, true, true, true, true]
]

# 起点位置
[start]
x = 0
y = 0

# 蓝宝石位置
[[blueGems]]
    x = 2
    y = 2

[[blueGems]]
    x = 4
    y = 0

[[blueGems]]
    x = 0
    y = 4

# 红宝石位置
[[redGems]]
    x = 0
    y = 2

[[redGems]]
    x = 2
    y = 0

[[redGems]]
    x = 4
    y = 4

# 怪物位置
[[monsters]]    
    x = 2
    y = 1

[[monsters]]
    x = 2
    y = 3

# 出口位置
[exit]
    x = 4
    y = 2

# 所需宝石数量
[requiredBlueGems]
    count = 3

[requiredRedGems]
    count = 3 