title = "迷宫配置"

# 迷宫布局 (1: 可通过, 0: 墙壁)
maze = [
  [1, 1, 1],
  [1, 1, 1],
  [1, 1, 1],
]

# 起点坐标
start = { x = 0, y = 0 }

# 蓝宝石位置
blueGems = []

# 红宝石位置
redGems = []

# 怪物位置
monsters = [
]

# 终点坐标
exit = { x = 2, y = 2 }

# 所需宝石数量
requiredBlueGems = 0
requiredRedGems = 0