title = "多层迷宫配置"
teleportGates = [ [ { x = 3, y = 0, level = 0 }, { x = 1, y = 1, level = 0 } ] ]
requiredBlueGems = 2
requiredRedGems = 2

[start]
x = 0
y = 0
level = 0

[exit]
x = 3
y = 3
level = 0

[[levels]]
maze = [
  [ 1, 1, 1, 1 ],
  [ 1, 1, 1, 1 ],
  [ 1, 1, 1, 1 ],
  [ 1, 1, 1, 1 ]
]

  [[levels.blueGems]]
  x = 1
  y = 0

  [[levels.blueGems]]
  x = 2
  y = 0

  [[levels.redGems]]
  x = 0
  y = 1

  [[levels.redGems]]
  x = 0
  y = 2

  [[levels.monsters]]
  x = 2
  y = 1
