title = "迷宫配置 003"
maze = [
    [
        true,
        true,
        true,
        false,
        true,
        false,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        false,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        false,
        true,
    ],
    [
        true,
        true,
        true,
        false,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        false,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        false,
        false,
        true,
        false,
        true,
    ],
]
blueGems = [
    { x = 5, y = 4 },
    { x = 3, y = 2 },
    { x = 4, y = 1 },
    { x = 5, y = 7 },
]
redGems = [
    { x = 2, y = 1 },
    { x = 4, y = 4 },
    { x = 0, y = 1 },
    { x = 5, y = 6 },
    { x = 5, y = 3 },
]
monsters = [
    { x = 0, y = 7 },
    { x = 2, y = 2 },
    { x = 5, y = 1 },
]
requiredBlueGems = 4
requiredRedGems = 5

[start]
x = 0
y = 0

[exit]
x = 1
y = 0
