title = "迷宫配置 004"
maze = [
    [
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        true,
    ],
    [
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
    ],
    [
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
    ],
    [
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
    ],
    [
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
    ],
    [
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
    ],
]
blueGems = [
    { x = 4, y = 5 },
    { x = 4, y = 0 },
    { x = 3, y = 5 },
    { x = 7, y = 2 },
    { x = 4, y = 2 },
]
redGems = [
    { x = 7, y = 4 },
    { x = 1, y = 2 },
    { x = 3, y = 1 },
    { x = 6, y = 5 },
    { x = 1, y = 0 },
]
monsters = [
    { x = 1, y = 1 },
    { x = 0, y = 1 },
    { x = 7, y = 0 },
    { x = 6, y = 3 },
]
requiredBlueGems = 5
requiredRedGems = 5

[start]
x = 0
y = 0

[exit]
x = 3
y = 4
