title = "迷宫配置 005"
maze = [
    [
        true,
        true,
        true,
        false,
        true,
        true,
    ],
    [
        true,
        false,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        false,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        false,
        true,
    ],
    [
        true,
        true,
        true,
        false,
        true,
        true,
    ],
    [
        false,
        true,
        true,
        true,
        true,
        true,
    ],
]
blueGems = [
    { x = 3, y = 2 },
    { x = 4, y = 6 },
    { x = 1, y = 6 },
    { x = 5, y = 4 },
]
redGems = [
    { x = 2, y = 3 },
    { x = 4, y = 0 },
    { x = 5, y = 5 },
    { x = 2, y = 5 },
]
monsters = [
    { x = 1, y = 4 },
    { x = 2, y = 2 },
]
requiredBlueGems = 4
requiredRedGems = 4

[start]
x = 0
y = 0

[exit]
x = 3
y = 6
