title = "迷宫配置 007"
maze = [
    [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
    ],
]
blueGems = [
    { x = 6, y = 4 },
    { x = 6, y = 7 },
    { x = 5, y = 3 },
]
redGems = [
    { x = 1, y = 4 },
    { x = 5, y = 7 },
    { x = 6, y = 0 },
    { x = 0, y = 1 },
]
monsters = [
    { x = 7, y = 6 },
    { x = 2, y = 1 },
]
requiredBlueGems = 3
requiredRedGems = 4

[start]
x = 0
y = 0

[exit]
x = 7
y = 1
