title = "迷宫配置 008"
maze = [
    [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
    ],
    [
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
    ],
    [
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
    ],
]
blueGems = [
    { x = 5, y = 1 },
    { x = 2, y = 5 },
    { x = 0, y = 4 },
    { x = 0, y = 3 },
    { x = 0, y = 5 },
]
redGems = [
    { x = 6, y = 1 },
    { x = 2, y = 2 },
    { x = 4, y = 4 },
    { x = 0, y = 1 },
]
monsters = [
    { x = 2, y = 3 },
    { x = 5, y = 4 },
]
requiredBlueGems = 5
requiredRedGems = 4

[start]
x = 0
y = 0

[exit]
x = 2
y = 0
