title = "迷宫配置 014"
maze = [
    [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        false,
        false,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        false,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        false,
        true,
        true,
        false,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        false,
        true,
        true,
    ],
]
blueGems = [
    { x = 3, y = 1 },
    { x = 6, y = 4 },
    { x = 3, y = 6 },
]
redGems = [
    { x = 4, y = 1 },
    { x = 2, y = 0 },
    { x = 5, y = 0 },
    { x = 3, y = 4 },
]
monsters = [
    { x = 3, y = 2 },
    { x = 5, y = 2 },
    { x = 5, y = 5 },
]
requiredBlueGems = 3
requiredRedGems = 4

[start]
x = 0
y = 0

[exit]
x = 4
y = 3
