title = "迷宫配置"
maze = [
  [ 1, 1, 1, 1, 0, 0, 1 ],
  [ 1, 1, 1, 0, 1, 0, 0 ],
  [ 1, 1, 0, 1, 0, 0, 1 ],
  [ 0, 1, 1, 1, 1, 1, 1 ],
  [ 1, 1, 0, 1, 0, 1, 1 ],
  [ 1, 0, 0, 1, 0, 1, 1 ],
  [ 1, 1, 1, 1, 0, 1, 1 ],
  [ 0, 1, 1, 0, 0, 1, 0 ]
]
requiredBlueGems = 5
requiredRedGems = 5

[start]
x = 0
y = 0

[[blueGems]]
x = 6
y = 2

[[blueGems]]
x = 2
y = 0

[[blueGems]]
x = 1
y = 6

[[blueGems]]
x = 1
y = 2

[[blueGems]]
x = 5
y = 6

[[redGems]]
x = 1
y = 3

[[redGems]]
x = 1
y = 7

[[redGems]]
x = 2
y = 7

[[redGems]]
x = 1
y = 0

[[redGems]]
x = 0
y = 5

[[monsters]]
x = 2
y = 3

[[monsters]]
x = 2
y = 1

[exit]
x = 0
y = 1
