title = "迷宫配置 018"
maze = [
    [
        true,
        true,
        true,
        true,
        false,
        false,
    ],
    [
        true,
        false,
        true,
        false,
        true,
        true,
    ],
    [
        false,
        true,
        false,
        false,
        false,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        false,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        false,
        false,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
    ],
]
blueGems = [
    { x = 2, y = 0 },
    { x = 3, y = 6 },
    { x = 3, y = 0 },
]
redGems = [
    { x = 5, y = 5 },
    { x = 2, y = 4 },
    { x = 5, y = 7 },
]
monsters = [
    { x = 4, y = 3 },
    { x = 0, y = 1 },
]
requiredBlueGems = 3
requiredRedGems = 3

[start]
x = 0
y = 0

[exit]
x = 0
y = 4
