title = "迷宫配置 021"
maze = [
    [
        true,
        true,
        true,
        false,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
    ],
    [
        false,
        false,
        false,
        true,
        true,
        false,
        true,
    ],
    [
        true,
        false,
        true,
        false,
        true,
        true,
        true,
    ],
    [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
    ],
    [
        true,
        false,
        true,
        true,
        true,
        false,
        false,
    ],
]
blueGems = [
    { x = 1, y = 2 },
    { x = 3, y = 5 },
    { x = 6, y = 1 },
]
redGems = [
    { x = 6, y = 0 },
    { x = 0, y = 1 },
    { x = 4, y = 6 },
    { x = 4, y = 2 },
]
monsters = [
    { x = 3, y = 3 },
    { x = 2, y = 5 },
]
requiredBlueGems = 3
requiredRedGems = 4

[start]
x = 0
y = 0

[exit]
x = 0
y = 4
