title = "迷宫配置"

# 迷宫布局 (1: 可通过, 0: 墙壁)
maze = [
  [1, 1, 1, 1, 1, 1, 1, 1],
  [1, 1, 0, 1, 1, 1, 1, 1],
  [1, 1, 0, 1, 1, 1, 1, 1],
  [1, 1, 0, 1, 1, 1, 1, 1],
  [1, 1, 0, 1, 1, 1, 1, 1],
  [1, 1, 0, 1, 1, 1, 1, 1],
  [1, 1, 0, 1, 1, 1, 1, 1],
  [0, 0, 0, 0, 0, 0, 0, 0],
]

# 起点坐标
start = { x = 0, y = 6 }

# 蓝宝石位置
blueGems = [
  { x = 1, y = 3 },
  { x = 1, y = 4 },
  { x = 1, y = 5 },
]

# 红宝石位置
redGems = [
  { x = 4, y = 4 },
  { x = 4, y = 5 },
]

# 怪物位置
monsters = [
]

# 终点坐标
exit = { x = 7, y = 5 }

# 所需宝石数量
requiredBlueGems = 3
requiredRedGems = 2