title = "迷宫配置"

# 迷宫布局 (1: 可通过, 0: 墙壁)
maze = [
  [1, 0, 0, 0, 0, 1, 1, 0],
  [1, 1, 1, 1, 1, 0, 0, 0],
  [1, 0, 1, 1, 0, 1, 0, 1],
  [1, 0, 0, 1, 1, 1, 0, 0],
  [1, 1, 0, 0, 1, 0, 0, 1],
  [1, 1, 1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1, 1, 1],
  [1, 1, 1, 1, 1, 1, 1, 1],
]

# 起点坐标
start = { x = 7, y = 6 }

# 蓝宝石位置
blueGems = [
  { x = 5, y = 2 },
  { x = 6, y = 0 },
  { x = 7, y = 2 },
  { x = 4, y = 3 },
  { x = 3, y = 2 },
  { x = 2, y = 2 },
  { x = 3, y = 3 },
  { x = 4, y = 4 },
]

# 红宝石位置
redGems = [
  { x = 0, y = 6 },
  { x = 0, y = 5 },
  { x = 2, y = 5 },
  { x = 3, y = 5 },
]

# 怪物位置
monsters = [
  { x = 5, y = 6 },
  { x = 4, y = 6 },
  { x = 4, y = 5 },
  { x = 5, y = 5 },
  { x = 6, y = 5 },
  { x = 6, y = 6 },
  { x = 6, y = 7 },
  { x = 5, y = 7 },
  { x = 4, y = 7 },
  { x = 3, y = 7 },
  { x = 1, y = 7 },
  { x = 2, y = 7 },
  { x = 2, y = 6 },
  { x = 3, y = 6 },
]

# 终点坐标
exit = { x = 0, y = 1 }

# 所需宝石数量
requiredBlueGems = 8
requiredRedGems = 4